### ISSUE TITLE
AttributeError: module 'heimdall' has no attribute 'png'

### ISSUE THREAD

**Issue by Kamik423** [DistilledLtd/heimdall#1]
somehow something appears to be broken with the import system. I installed with pip, and verified that it is.

```python
#! /usr/bin/env python3

import heimdall

screenshot = heimdall.png('<myurl>', device='Laptop')
```

This yields

```
AttributeError: module 'heimdall' has no attribute 'png'
```

**Comment by duncanmorris** [comment]
I'm afraid this isn't a library we are actively using or supporting at the moment.

Having said that, I'm fairly sure this will only work with python2.
